import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { api, type ActivityEvent, type KnowledgeGap } from "../api/client";
export default function KnowledgeGapsPanel({ events }: { events: ActivityEvent[] }) {
  const [gaps, setGaps] = useState<KnowledgeGap[] | null>(null); const [active, setActive] = useState<string | null>(null); const [note, setNote] = useState("");
  useEffect(() => { api.getKnowledgeGaps().then(v => setGaps(Array.isArray(v) ? v : v.gaps)).catch(() => setGaps([])); }, []);
  useEffect(() => { events.filter(e => e.type === "knowledge_gap").forEach(event => { const data = event.data as KnowledgeGap | undefined; if (data?.id) setGaps(current => current && [data, ...current.filter(g => g.id !== data.id)]); }); }, [events]);
  const resolve = async (id: string) => { try { await api.resolveKnowledgeGap(id, note); setGaps(g => g?.filter(x => x.id !== id) ?? []); setActive(null); setNote(""); } catch { /* keep available */ } };
  return <section className="app-panel p-6"><div className="mb-5 flex justify-between"><h2 className="app-section-label">Knowledge gaps</h2><span className="text-[10px] text-[#9a9a8a]">{gaps?.length ?? "0"} open</span></div>{gaps === null ? <div className="h-16 animate-pulse bg-[#f0ede6]" /> : gaps.length === 0 ? <p className="border-t border-[#f0ede6] pt-4 text-sm text-[#9a9a8a]">No open gaps. Your agent can answer everything customers are asking.</p> : <AnimatePresence>{gaps.map(gap => <motion.div exit={{ opacity: 0, x: 20 }} key={gap.id} className="border-t border-[#f0ede6] py-4"><button onClick={() => setActive(active === gap.id ? null : gap.id)} className="flex w-full items-center gap-3 text-left"><span className="inline-block h-1.5 w-1.5 rounded-full bg-[#5a7a5a]" /><span className="text-sm text-[#1a1a1a]">"{gap.question}"</span></button>{active === gap.id && <div className="mt-3 flex gap-2 pl-5"><input value={note} onChange={e => setNote(e.target.value)} placeholder="Mark resolved with a note" className="app-input" /><button onClick={() => resolve(gap.id)} className="app-btn-primary shrink-0">Save</button></div>}</motion.div>)}</AnimatePresence>}</section>;
}
