import { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import ToneSelector from "../components/ToneSelector";
import WhatsAppPreview from "../components/WhatsAppPreview";
import { api, type BotSettings } from "../api/client";
const defaults: BotSettings = { agent_name: "Zara", agent_personality: "Warm and knowledgeable about beekeeping. You speak to customers like a helpful friend who happens to know everything about bees.", agent_greeting: "Hi there! 🐝 I'm Zara from Macaney. How can I help you today?", agent_language_style: "friendly" };
const businessTypes = ["Retail", "Wholesale", "School", "Hospital", "Clinic", "Events", "Restaurant", "Services", "Real Estate", "Logistics"];
export default function BotSettings() { const [form, setForm] = useState(defaults); const [type, setType] = useState("Retail"); const [extended, setExtended] = useState<Record<string, string>>({}); const [status, setStatus] = useState(""); useEffect(() => { api.getBotSettings().then(setForm).catch(() => undefined); api.getExtendedBrain().then(v => { if (v.business_type) setType(v.business_type); setExtended(v); }).catch(() => undefined); }, []); const edit = (field: keyof BotSettings, value: string) => setForm(v => ({ ...v, [field]: value })); const save = async () => { setStatus(""); try { await Promise.all([api.updateBotSettings(form), api.updateExtendedBrain({ business_type: type, ...extended })]); setStatus("Saved ✓"); setTimeout(() => setStatus(""), 2000); } catch { setStatus("Could not save changes. Please try again."); } }; const fields = type === "School" ? ["Term dates", "Admission requirements", "Fee structure"] : type === "Restaurant" ? ["Menu", "Opening hours", "Delivery areas"] : type === "Logistics" ? ["Service areas", "Rate card", "Delivery times"] : ["Business policies", "Operating hours"];
return <main className="min-h-screen bg-[#f5f4ef] text-[#1a1a1a]"><Navbar /><div className="mx-auto max-w-5xl px-10 py-10"><p className="app-section-label">Agent configuration</p><h1 className="mt-2 text-3xl font-light">Bot Identity</h1><div className="mt-8 grid grid-cols-[1fr_360px] gap-8"><section className="app-panel p-8"><Field label="Bot name" help="This is the name your bot uses when greeting customers." count={`${form.agent_name.length}/40`}><input maxLength={40} value={form.agent_name} onChange={e => edit("agent_name", e.target.value)} className="app-input" /></Field><Field label="Personality" help="Describe your bot's character." count={`${form.agent_personality.length}/500`}><textarea maxLength={500} rows={5} value={form.agent_personality} onChange={e => edit("agent_personality", e.target.value)} className="app-input resize-none" /></Field><Field label="Greeting message" help="Sent automatically when a new customer messages you." count={`${form.agent_greeting.length}/300`}><textarea maxLength={300} rows={3} value={form.agent_greeting} onChange={e => edit("agent_greeting", e.target.value)} className="app-input resize-none" /></Field><div className="mb-6"><label className="app-section-label mb-2 block">Tone</label><ToneSelector value={form.agent_language_style} onChange={value => edit("agent_language_style", value)} /></div><div className="border-t border-[#f0ede6] pt-6"><label className="app-section-label mb-2 block">Business type</label><div className="flex flex-wrap gap-2">{businessTypes.map(item => <button key={item} onClick={() => setType(item)} className={`rounded-sm border px-3 py-1.5 text-[11px] ${type === item ? "border-[#5a7a5a] bg-[#5a7a5a] text-white" : "border-[#e0ddd6] bg-white text-[#1a1a1a]"}`}>{item}</button>)}</div><div className="mt-5 grid grid-cols-2 gap-4">{fields.map(field => <label key={field} className="app-section-label">{field}<input value={extended[field] ?? ""} onChange={e => setExtended(v => ({ ...v, [field]: e.target.value }))} className="app-input mt-2" /></label>)}</div></div><div className="flex items-center justify-end gap-4 pt-7"><span className={`text-xs ${status.startsWith("Saved") ? "text-[#5a7a5a]" : "text-red-400"}`}>{status}</span><button onClick={save} className="app-btn-primary">Save changes</button></div></section><aside><p className="app-section-label mb-3">WhatsApp preview</p><WhatsAppPreview settings={form} /></aside></div></div></main>; }
function Field({ label, help, count, children }: { label: string; help: string; count: string; children: React.ReactNode }) { return <div className="mb-6"><label className="app-section-label mb-2 block">{label}</label>{children}<div className="mt-1.5 flex justify-between text-xs text-[#9a9a8a]"><span>{help}</span><span>{count}</span></div></div>; }
