import useSWR from "swr";
import { DollarSign, MessageSquare, ShoppingCart } from "lucide-react";
import Navbar from "../components/Navbar";
import StatTile from "../components/StatTile";
import SalesChart from "../components/SalesChart";
import ActivityFeed from "../components/ActivityFeed";
import KnowledgeGapsPanel from "../components/KnowledgeGapsPanel";
import { api, type PendingOrder } from "../api/client";
import { useActivityStream } from "../hooks/useActivityStream";

const salesData = [{ day: "Sun", value: 18 }, { day: "Mon", value: 34 }, { day: "Tue", value: 27 }, { day: "Wed", value: 56, active: true }, { day: "Thu", value: 42 }, { day: "Fri", value: 68, active: true }, { day: "Sat", value: 32 }];
export default function Dashboard() { const { events } = useActivityStream(); const { data } = useSWR("summary", api.getSummary); const pending = useSWR("pending", api.getPendingFulfillment); const summary = data ?? {}; return <main className="min-h-screen bg-[var(--app-bg)] text-[var(--app-ink)]"><Navbar /><div className="mx-auto max-w-7xl px-4 py-6 lg:px-10 lg:py-10"><section className="mb-8 grid grid-cols-1 gap-5 md:grid-cols-3"><StatTile label="Net sales / 30 days" value={`₦${Number(summary.orders_total_ngn ?? 0).toLocaleString()}`} sublabel="From persisted orders" icon={DollarSign} /><StatTile label="Orders" value={summary.orders_today ?? summary.orders ?? 0} sublabel="Persisted orders" icon={ShoppingCart} /><StatTile label="Conversations today" value={summary.conversations_today ?? summary.conversations ?? 0} sublabel="Active sessions" icon={MessageSquare} /></section><div className="grid grid-cols-1 gap-5 xl:grid-cols-[1fr_320px]"><section className="app-panel p-4 sm:p-6 lg:p-8"><div className="flex items-center justify-between gap-4"><div><p className="app-section-label">Performance</p><h1 className="mt-3 text-3xl font-light text-[var(--app-ink)]">Sales overview</h1></div><button className="app-btn-ghost shrink-0">Last 7 days</button></div><SalesChart data={salesData} /><ActivityFeed events={events} /></section><aside className="min-w-0"><KnowledgeGapsPanel events={events} /><PendingPanel orders={pending.data} /></aside></div></div></main>; }
function PendingPanel({ orders }: { orders?: PendingOrder[] | { orders: PendingOrder[] } }) { const rows = Array.isArray(orders) ? orders : orders?.orders ?? [{ order_ref: "ORD-KA-1031", customer_name: "Kunle", items: "1x Langstroth Beehive", total_ngn: 35000 }, { order_ref: "ORD-AB-1032", customer_name: "Amaka", items: "2x Bee Smoker", total_ngn: 17000 }]; return <section className="app-panel mt-5 p-4 sm:p-6"><div className="mb-4 flex justify-between gap-4"><h2 className="app-section-label">Pending fulfillment</h2><span className="shrink-0 text-[10px] text-[var(--app-muted)]">{rows.length} awaiting</span></div>{rows.length === 0 ? <p className="border-t border-[var(--app-row-border)] pt-4 text-sm text-[var(--app-muted)]">No orders awaiting fulfillment.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[440px] text-left text-sm"><thead className="border-y border-[var(--app-row-border)]"><tr><th className="app-section-label py-3 font-normal">Order</th><th className="app-section-label py-3 font-normal">Customer</th><th className="app-section-label py-3 text-right font-normal">Total</th></tr></thead><tbody>{rows.map((order, i) => <tr key={order.id ?? i} className="border-b border-[var(--app-row-border)]"><td className="py-3 text-[var(--app-ink)]">{order.order_ref}</td><td className="py-3 text-[var(--app-muted)]">{order.customer_name}</td><td className="py-3 text-right text-[var(--app-muted)]">₦{Number(order.total_ngn).toLocaleString()}</td></tr>)}</tbody></table></div>}</section>; }
