import useSWR from "swr";
import { DollarSign, MessageSquare, ShoppingCart } from "lucide-react";
import Navbar from "../components/Navbar";
import StatTile from "../components/StatTile";
import SalesChart from "../components/SalesChart";
import ActivityFeed from "../components/ActivityFeed";
import KnowledgeGapsPanel from "../components/KnowledgeGapsPanel";
import { api, type PendingOrder } from "../api/client";
import { useActivityStream } from "../hooks/useActivityStream";

const salesData = [{ day: "Sun", value: 18 }, { day: "Mon", value: 34 }, { day: "Tue", value: 27 }, { day: "Wed", value: 56, active: true }, { day: "Thu", value: 42 }, { day: "Fri", value: 68, active: true }, { day: "Sat", value: 32 }];
export default function Dashboard() { const { events } = useActivityStream(); const { data } = useSWR("summary", api.getSummary); const pending = useSWR("pending", api.getPendingFulfillment); const summary = data ?? {}; return <main className="min-h-screen bg-[var(--app-bg)] text-[var(--app-ink)]"><Navbar /><div className="mx-auto max-w-7xl px-10 py-10"><section className="mb-8 grid grid-cols-3 gap-5"><StatTile label="Net sales / 30 days" value={`₦${Number(summary.orders_total_ngn ?? 0).toLocaleString()}`} sublabel="From persisted orders" icon={DollarSign} /><StatTile label="Orders" value={summary.orders_today ?? summary.orders ?? 0} sublabel="Persisted orders" icon={ShoppingCart} /><StatTile label="Conversations today" value={summary.conversations_today ?? summary.conversations ?? 0} sublabel="Active sessions" icon={MessageSquare} /></section><div className="grid grid-cols-[1fr_320px] gap-5"><section className="app-panel p-8"><div className="flex items-center justify-between"><div><p className="app-section-label">Performance</p><h1 className="mt-3 text-3xl font-light text-[var(--app-ink)]">Sales overview</h1></div><button className="app-btn-ghost">Last 7 days</button></div><SalesChart data={salesData} /><ActivityFeed events={events} /></section><aside><KnowledgeGapsPanel events={events} /><PendingPanel orders={pending.data} /></aside></div></div></main>; }
function PendingPanel({ orders }: { orders?: PendingOrder[] | { orders: PendingOrder[] } }) { const rows = Array.isArray(orders) ? orders : orders?.orders ?? [{ order_ref: "ORD-KA-1031", customer_name: "Kunle", items: "1x Langstroth Beehive", total_ngn: 35000 }, { order_ref: "ORD-AB-1032", customer_name: "Amaka", items: "2x Bee Smoker", total_ngn: 17000 }]; return <section className="app-panel mt-5 p-6"><div className="mb-4 flex justify-between"><h2 className="app-section-label">Pending fulfillment</h2><span className="text-[10px] text-[var(--app-muted)]">{rows.length} awaiting</span></div>{rows.length === 0 ? <p className="border-t border-[var(--app-row-border)] pt-4 text-sm text-[var(--app-muted)]">No orders awaiting fulfillment.</p> : rows.map((order, i) => <div key={order.id ?? i} className="border-t border-[var(--app-row-border)] py-3"><p className="text-sm text-[var(--app-ink)]">{order.order_ref}</p><p className="mt-1 text-xs text-[var(--app-muted)]">{order.customer_name} · ₦{Number(order.total_ngn).toLocaleString()}</p></div>)}</section>; }
